### ISSUE TITLE
Version Strangeness

### ISSUE THREAD

**Issue by behinger** [MakieOrg/MakieThemes.jl#20]
Hi!
I saw that in your project.toml version is still 0.0.1 - but in registry etc. it is 0.0.2

Maybe this is the reason I always get downgraded to CairoMakie 0.3 (super old) or GLMakie 0.1.3 (superold)?

Try it yourself e.g. in pluto

```julia
begin
	using Pkg
	using CairoMakie
	using MakieThemes
	#Figure()
	Pkg.resolve()
	Pkg.update()
	Pkg.status(;outdated=true)
end
```
`⌃ [13f3f980] CairoMakie v0.3.4 [<v0.3.19], (<v0.10.2)`

![image](https://user-images.githubusercontent.com/10183650/222159514-6058f568-b042-4d37-8374-fc274c09d61a.png)

If I manually run ]dev MakieThemes - it works though, indicating something messed up with the versioning - and the Project.toml missmatches, so maybe that is the issue?

Best, Benedikt

**Comment by asinghvi17** [comment]
So the version in Project.toml is v0.1.0, but I guess it didn't get registered for some reason...

**Comment by asinghvi17** [comment]
yeah, just opened a registration PR.  Should be good to go in some time.  Thanks for letting me know!

**Comment by behinger** [comment]
mh I dont understand - the Project.toml in this repo is still v0.0.1 (in the registry it is actualy 0.0.2 already) - if you now downgrade the registry, wouldnt that lead to some kind of complicatedness - skipping to 0.0.3 wouldnt have?

(this is really just to understand better how version management works in registries etc.)

**Comment by asinghvi17** [comment]
You might be looking at an old branch?  This is the current version:

https://github.com/MakieOrg/MakieThemes.jl/blob/e09a6eca8cdf2f277ab228d1dccfe4607b3f21e5/Project.toml#L4

**Comment by asinghvi17** [comment]
I've registered the new version in the registry now, it might take a little while to propagate though.

**Comment by behinger** [comment]
nono, missunderstanding.
I mean this:
https://github.com/JuliaRegistries/General/blob/master/M/MakieThemes/Versions.toml

Where there exists a v0.0.2 already. thus everyone will always install the v0.0.2 if you do add MakieThemes

**Comment by asinghvi17** [comment]
ah yeah, that's because the version 0.1.0 wasn't registered yet - if you take a look at it now, you should see an entry for v0.1.0.

Basically, you have to register the new version of a package when you want to release it.  This version is 0.1.0, which is higher than 0.0.2 (think of them not as decimals, but rather as triplets - 0-1-0 is higher in the natural search order than 0-0-2).
